{
 "title": "Mintter Networking",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "instance", "query": { "query": "label_values(up, instance)" } }
  ]
 },
 "panels": [
  { "title": "Syncing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sync Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(mintter_syncing_periodic_operations_total[$__rate_interval])",
     "legendFormat": "Total Rate - {{instance}}"
    },
    {
     "expr": "rate(mintter_syncing_periodic_errors_total[$__rate_interval])",
     "legendFormat": "Error Rate - {{instance}}"
    }
   ]
  },
  {
   "title": "Blobs Wanted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "mintter_syncing_wanted_blobs",
     "legendFormat": "Blobs Wanted ({{package}}) - {{instance}}"
    }
   ]
  },
  {
   "title": "Currently Established Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (transport) (libp2p_swarm_connections_opened_total{instance=~\"$instance\"}) - sum by (transport) (libp2p_swarm_connections_closed_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections: Inbound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (transport, security, muxer) (libp2p_swarm_connections_opened_total{dir=\"inbound\",instance=~\"$instance\"}) - sum by (transport, security, muxer) (libp2p_swarm_connections_closed_total{dir=\"inbound\",instance=~\"$instance\"})",
     "legendFormat": "{{transport}} {{security}} {{muxer}}"
    }
   ]
  },
  {
   "title": "Active Connections: Outgoing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (transport, security, muxer)(libp2p_swarm_connections_opened_total{dir=\"outbound\",instance=~\"$instance\"}) - sum by (transport, security, muxer) (libp2p_swarm_connections_closed_total{dir=\"outbound\",instance=~\"$instance\"})",
     "legendFormat": "{{transport}} {{security}} {{muxer}}"
    }
   ]
  },
  {
   "title": "Handshake Latency (QUIC, QUIC v1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(libp2p_swarm_handshake_latency_seconds_bucket{transport=~\"quic|quic-v1\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(libp2p_swarm_handshake_latency_seconds_bucket{transport=~\"quic|quic-v1\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(libp2p_swarm_handshake_latency_seconds_bucket{transport=~\"quic|quic-v1\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "95th percentile"
    }
   ]
  },
  {
   "title": "Handshake Latency (TCP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(libp2p_swarm_handshake_latency_seconds_bucket{transport=\"tcp\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(libp2p_swarm_handshake_latency_seconds_bucket{transport=\"tcp\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(libp2p_swarm_handshake_latency_seconds_bucket{transport=\"tcp\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "95th percentile"
    }
   ]
  },
  {
   "title": "Connection Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(libp2p_swarm_connection_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(libp2p_swarm_connection_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(libp2p_swarm_connection_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "95th percentile"
    }
   ]
  },
  {
   "title": "Active Connections: Early Muxer Negotiation",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(libp2p_swarm_connections_opened_total{transport=\"tcp\",early_muxer=\"true\",instance=~\"$instance\"} - libp2p_swarm_connections_closed_total{transport=\"tcp\",early_muxer=\"true\",instance=~\"$instance\"})",
     "legendFormat": "early muxer"
    },
    {
     "expr": "sum(libp2p_swarm_connections_opened_total{transport=\"tcp\",early_muxer=\"false\",instance=~\"$instance\"} - libp2p_swarm_connections_closed_total{transport=\"tcp\",early_muxer=\"false\",instance=~\"$instance\"})",
     "legendFormat": "regular"
    }
   ]
  },
  { "title": "Connection Establishment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "New Connections: Inbound",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum (rate(libp2p_swarm_connections_opened_total{dir=\"inbound\",instance=~\"$instance\"}[$__rate_interval])) by (transport, security, muxer)",
     "legendFormat": "{{transport}} {{security}} {{muxer}}"
    }
   ]
  },
  {
   "title": "New Connections: Outgoing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum (rate(libp2p_swarm_connections_opened_total{dir=\"outbound\",instance=~\"$instance\"}[$__rate_interval])) by (transport, security, muxer)",
     "legendFormat": "{{transport}} {{security}} {{muxer}}"
    }
   ]
  },
  {
   "title": "New Inbound Connections: Transports / Security / Muxers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(libp2p_swarm_connections_opened_total{dir=\"inbound\",instance=~\"$instance\"}[$__range])) by (transport, security, muxer)",
     "legendFormat": "{{transport}} {{security}} {{muxer}}"
    }
   ]
  },
  {
   "title": "New Outgoing Connections: Transports / Security / Muxers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(libp2p_swarm_connections_opened_total{dir=\"outbound\",instance=~\"$instance\"}[$__range])) by (transport, security, muxer)",
     "legendFormat": "{{transport}} {{security}} {{muxer}}"
    }
   ]
  },
  {
   "title": "New Inbound Connections: IP Version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ip_version) (libp2p_swarm_connections_opened_total{dir=\"inbound\",instance=~\"$instance\"}) - sum by (ip_version) (libp2p_swarm_connections_closed_total{dir=\"inbound\",instance=~\"$instance\"})",
     "legendFormat": "{{ip_version}}"
    }
   ]
  },
  {
   "title": "New Outbound Connections: IP Version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ip_version) (libp2p_swarm_connections_opened_total{dir=\"outbound\",instance=~\"$instance\"}) - sum by (ip_version) (libp2p_swarm_connections_closed_total{dir=\"outbound\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dial Errors",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(libp2p_swarm_dial_errors_total{instance=~\"$instance\"}[$__range])) by (error)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dial Success Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(libp2p_swarm_connections_opened_total{dir=\"outbound\",instance=~\"$instance\"}[$__rate_interval])) by (transport)  / (sum(rate(libp2p_swarm_connections_opened_total{dir=\"outbound\",instance=~\"$instance\"}[$__rate_interval])) by (transport) + (sum(rate(libp2p_swarm_dial_errors_total{instance=~\"$instance\"}[$__rate_interval])) by (transport)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "libp2p key types",
   "type": "piechart",
   "description": "on newly established connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (key_type) (increase(libp2p_swarm_key_types_total{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "{{key_type}}"
    }
   ]
  },
  { "title": "Dial Prioritisation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Dial Ranking Delay",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(libp2p_swarm_dial_ranking_delay_seconds_bucket{instance=~\"$instance\",le=\"0.001\"}[$__range]))",
     "legendFormat": "No delay"
    },
    {
     "expr": "sum(increase(libp2p_swarm_dial_ranking_delay_seconds_bucket{instance=~\"$instance\",le=\"0.01\"}[$__range])) - ignoring(le) sum(increase(libp2p_swarm_dial_ranking_delay_seconds_bucket{instance=~\"$instance\",le=\"0.001\"}[$__range]))",
     "legendFormat": "<=10ms"
    },
    {
     "expr": "sum(increase(libp2p_swarm_dial_ranking_delay_seconds_bucket{instance=~\"$instance\",le=\"0.05\"}[$__range])) - ignoring(le) sum(increase(libp2p_swarm_dial_ranking_delay_seconds_bucket{instance=~\"$instance\",le=\"0.01\"}[$__range]))",
     "legendFormat": "<=50ms"
    },
    {
     "expr": "sum(increase(libp2p_swarm_dial_ranking_delay_seconds_bucket{instance=~\"$instance\",le=\"0.3\"}[$__range])) - ignoring(le) sum(increase(libp2p_swarm_dial_ranking_delay_seconds_bucket{instance=~\"$instance\",le=\"0.05\"}[$__range]))",
     "legendFormat": "<=300ms"
    },
    {
     "expr": "sum(increase(libp2p_swarm_dial_ranking_delay_seconds_bucket{instance=~\"$instance\",le=\"0.5\"}[$__range])) - ignoring(le) sum(increase(libp2p_swarm_dial_ranking_delay_seconds_bucket{instance=~\"$instance\",le=\"0.3\"}[$__range]))",
     "legendFormat": "<=500ms"
    },
    {
     "expr": "sum(increase(libp2p_swarm_dial_ranking_delay_seconds_bucket{instance=~\"$instance\",le=\"0.75\"}[$__range])) - ignoring(le) sum(increase(libp2p_swarm_dial_ranking_delay_seconds_bucket{instance=~\"$instance\",le=\"0.5\"}[$__range]))",
     "legendFormat": "<=750ms"
    },
    {
     "expr": "sum(increase(libp2p_swarm_dial_ranking_delay_seconds_bucket{instance=~\"$instance\",le=\"+Inf\"}[$__range])) - ignoring(le) sum(increase(libp2p_swarm_dial_ranking_delay_seconds_bucket{instance=~\"$instance\",le=\"0.75\"}[$__range]))",
     "legendFormat": ">750ms"
    }
   ]
  },
  {
   "title": "Dials per connection",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(libp2p_swarm_dials_per_peer_total{instance=~\"$instance\", outcome=\"success\", num_dials=\"0\"}[$__range])",
     "legendFormat": "0"
    },
    {
     "expr": "increase(libp2p_swarm_dials_per_peer_total{instance=~\"$instance\", outcome=\"success\", num_dials=\"1\"}[$__range])",
     "legendFormat": "1"
    },
    {
     "expr": "increase(libp2p_swarm_dials_per_peer_total{instance=~\"$instance\", outcome=\"success\", num_dials=\"2\"}[$__range])",
     "legendFormat": "2"
    },
    {
     "expr": "increase(libp2p_swarm_dials_per_peer_total{instance=~\"$instance\", outcome=\"success\", num_dials=\"3\"}[$__range])",
     "legendFormat": "3"
    },
    {
     "expr": "increase(libp2p_swarm_dials_per_peer_total{instance=~\"$instance\", outcome=\"success\", num_dials=\"4\"}[$__range])",
     "legendFormat": "4"
    },
    {
     "expr": "increase(libp2p_swarm_dials_per_peer_total{instance=~\"$instance\", outcome=\"success\", num_dials=\"5\"}[$__range])",
     "legendFormat": "5"
    },
    {
     "expr": "increase(libp2p_swarm_dials_per_peer_total{instance=~\"$instance\", outcome=\"success\", num_dials=\">=6\"}[$__range])",
     "legendFormat": ">=6"
    }
   ]
  },
  { "title": "Black Hole Detection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Black Hole Filter State",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "libp2p_swarm_black_hole_filter_state{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Black Hole Filter Requests Till Next Probe",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_swarm_black_hole_filter_next_request_allowed_after{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: {{name}}"
    }
   ]
  },
  {
   "title": "Dial Success Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_swarm_black_hole_filter_success_fraction{instance=~\"$instance\"} * 100",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  }
 ]
}