{
 "title": "Mintter P2P",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "instance", "query": { "query": "label_values(up, instance)" } }
  ]
 },
 "panels": [
  { "title": "Syncing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sync Operations (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(mintter_syncing_periodic_operations_total[$__rate_interval])",
     "legendFormat": "Total Rate - {{instance}}"
    },
    {
     "expr": "rate(mintter_syncing_periodic_errors_total[$__rate_interval])",
     "legendFormat": "Error Rate - {{instance}}"
    }
   ]
  },
  {
   "title": "Connection Attempts (In-Flight)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "mintter_syncing_connects_in_flight",
     "legendFormat": "Attempts - {{instance}}"
    }
   ]
  },
  {
   "title": "Blobs Wanted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "mintter_syncing_wanted_blobs",
     "legendFormat": "Blobs Wanted ({{package}}) - {{instance}}"
    }
   ]
  },
  { "title": "Libp2p", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "libp2p_open_connections",
     "legendFormat": "Open Connections - {{instance}}"
    }
   ]
  },
  {
   "title": "Peer Routing Calls (In-Flight)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "libp2p_routing_find_peer_requests_in_flight",
     "legendFormat": "Calls - {{instance}}"
    }
   ]
  },
  {
   "title": "Peer Routing Calls (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "rate(libp2p_routing_find_peer_requests_total[$__rate_interval])",
     "legendFormat": "Total Rate - {{instance}}"
    },
    {
     "expr": "rate(libp2p_routing_find_peer_requests_errors_total[$__rate_interval])",
     "legendFormat": "Error Rate - {{instance}}"
    }
   ]
  }
 ]
}