export const nodeTypes = {
  typeP: 'p',
  typeBlockquote: 'blockquote',
  typeLink: 'link',
  typeImg: 'img',
  typeUl: 'ul',
  typeOl: 'ol',
  typeLi: 'li',
  typeH1: 'h1',
  typeH2: 'h2',
  typeH3: 'h3',
  typeBlock: 'block',
  typeCodeBlock: 'code_block',
  typeTable: 'table',
  // marks
  typeBold: 'bold',
  typeItalic: 'italic',
  typeUnderline: 'underline',
  typeStrikethrough: 'strikethrough',
  typeCode: 'code',
};
