enum error { 
    /// Errno::Ilseq: Illegal byte sequence
    ilseq,
    /// Errno::Inval: Invalid argument
    inval,
    /// Errno::Overflow: Value too large to be stored in data type.
    overflow,
    /// Errno::Io: I/O error
    io,
    /// Errno::Badf: Bad file descriptor
    badf,
    /// Broken Pipe.
    pipe,
    /// Errno::Perm: Permission denied
    perm,
}