/// This interface gives extensions access to the unified logging system that is used by the WebView, Rust Host and Go daemon too.
/// Log levels mirror the ones commonly used in Rust.

use { error } from error

enum log-level {
  trace,
  debug,
  info,
  warn,
  error,
}

/// Logs a message to the unified logging system used by mintter.
log: func(level: log-level, str: string) -> result<_, error>