// The pledge interface allows extensions to declare a set of `Promises` that limit the scope of APIs it has access to.
// Accessing a function without the proper permission for it will immeditately terminate the extension with the `PERM` error.
// 
// This API is inpsired by the pledge&unveil syscalls from BSD.

use { error } from error

/// The permissions defined here are broader than what is currently used in the app
/// They are mainly here for future proofing, so additions in APIs are not breaking changes to older extensions.
flags promises {
    /// Basic I/O
    stdio,
    /// „Read“ filesystem access
    rpath,
    /// „Write“ filesystem access
    wpath,
    /// „Create“ filesystem access
    cpath,
    /// Access to temporary files
    tmppath,
    /// IPv4 & IPv6 sockets
    inet,
    /// DNS network transactions
    dns,
    /// Access to `exit()`
    proc,
    /// Access to system device info (like CPU info)
    sysinfo,
    /// Audio devices
    audio,
    /// Video devices
    video,
    /// Access to the lightning API
    lightning,
    /// „Read“ content graph access
    rgraph,
    /// „Write“ content graph access
    wgraph,
    /// „Create“ content graph access
    cgraph,
    /// Access to the fetch API
    fetch,
}

pledge: func(promises: promises) -> result<_, error>