import {
  blue,
  blueDark,
  gray,
  grayDark,
  green,
  greenDark,
  orange,
  orangeDark,
  red,
  redDark,
  yellow,
  yellowDark
} from '@radix-ui/colors'
import type * as Stitches from '@stitches/react'
import { createStitches, defaultThemeMap } from '@stitches/react'

const stitches = createStitches({
  prefix: 'mtt',
  theme: {
    borderStyles: {},
    borderWidths: {},
    colors: {
      'base-background-subtle': gray.gray1,
      'base-background-normal': gray.gray2,
      'base-component-bg-normal': gray.gray3,
      'base-component-bg-hover': gray.gray4,
      'base-component-bg-active': gray.gray5,
      'base-border-subtle': gray.gray6,
      'base-border-normal': gray.gray7,
      'base-border-hover': gray.gray8,
      'base-normal': gray.gray9,
      'base-active': gray.gray10,
      'base-text-low': gray.gray11,
      'base-text-high': gray.gray12,
      'base-text-opposite': gray.gray1,

      'primary-background-subtle': blue.blue1,
      'primary-background-normal': blue.blue2,
      'primary-component-bg-normal': blue.blue3,
      'primary-component-bg-hover': blue.blue4,
      'primary-component-bg-active': blue.blue5,
      'primary-border-subtle': blue.blue6,
      'primary-border-normal': blue.blue7,
      'primary-border-hover': blue.blue8,
      'primary-normal': blue.blue9,
      'primary-active': blue.blue10,
      'primary-text-low': blue.blue11,
      'primary-text-high': blue.blue12,
      'primary-text-opposite': blue.blue1,

      'secondary-background-subtle': orange.orange1,
      'secondary-background-normal': orange.orange2,
      'secondary-component-bg-normal': orange.orange3,
      'secondary-component-bg-hover': orange.orange4,
      'secondary-component-bg-active': orange.orange5,
      'secondary-border-subtle': orange.orange6,
      'secondary-border-normal': orange.orange7,
      'secondary-border-hover': orange.orange8,
      'secondary-normal': orange.orange9,
      'secondary-active': orange.orange10,
      'secondary-text-low': orange.orange11,
      'secondary-text-high': orange.orange12,
      'secondary-text-opposite': orange.orange1,

      'success-background-subtle': green.green1,
      'success-background-normal': green.green2,
      'success-component-bg-normal': green.green3,
      'success-component-bg-hover': green.green4,
      'success-component-bg-active': green.green5,
      'success-border-subtle': green.green6,
      'success-border-normal': green.green7,
      'success-border-hover': green.green8,
      'success-normal': green.green9,
      'success-active': green.green10,
      'success-text-low': green.green11,
      'success-text-high': green.green12,
      'success-text-opposite': green.green1,

      'warning-background-subtle': yellow.yellow1,
      'warning-background-normal': yellow.yellow2,
      'warning-component-bg-normal': yellow.yellow3,
      'warning-component-bg-hover': yellow.yellow4,
      'warning-component-bg-active': yellow.yellow5,
      'warning-border-subtle': yellow.yellow6,
      'warning-border-normal': yellow.yellow7,
      'warning-border-hover': yellow.yellow8,
      'warning-normal': yellow.yellow9,
      'warning-active': yellow.yellow10,
      'warning-text-low': yellow.yellow11,
      'warning-text-high': yellow.yellow12,
      'warning-text-opposite': yellow.yellow1,

      'danger-background-subtle': red.red1,
      'danger-background-normal': red.red2,
      'danger-component-bg-normal': red.red3,
      'danger-component-bg-hover': red.red4,
      'danger-component-bg-active': red.red5,
      'danger-border-subtle': red.red6,
      'danger-border-normal': red.red7,
      'danger-border-hover': red.red8,
      'danger-normal': red.red9,
      'danger-active': red.red10,
      'danger-text-low': red.red11,
      'danger-text-high': red.red12,
      'danger-text-opposite': red.red1,
    },
    fonts: {
      base: `-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial,
      sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji'`,
      alt: `Iowan Old Style, Apple Garamond, Baskerville, Times New Roman, Droid
      Serif, Times, Source Serif Pro, serif, Apple Color Emoji, Segoe UI Emoji, Segoe
      UI Symbol`,
    },
    fontSizes: {
      1: '12px',
      2: '14px',
      3: '16px',
      4: '20px',
      5: '24px',
      6: '32px',
      7: '48px',
    },
    fontWeights: {
      regular: 400,
      medium: 500,
      bold: 700,
    },
    letterSpacings: {},
    lineHeights: {
      1: '1.2',
      2: '1.4',
      3: '1.5',
      4: '2',
    },
    radii: {
      1: '3px',
      2: '5px',
      3: '7px',
      round: '50%',
      pill: '9999px',
    },
    shadows: {
      focus: '0 0 0 2px $colors$primary-border-hover',
      menu: '0px 4px 8px $colors$base-component-bg-active',
      3: '0px 4px 8px $colors$base-component-bg-active',
    },
    sizes: {
      none: '0px',
      'one-quarter': '25%',
      'one-third': '33.333%',
      half: '50%',
      'two-thirds': '66.6666%',
      'three-quarters': '75%',
      full: '100%',
      'prose-width': '70ch',
      'library-width': '232px',
    },
    space: {
      0: 0,
      1: '2px',
      2: '4px',
      3: '8px',
      4: '12px',
      5: '16px',
      6: '20px',
      7: '24px',
      8: '32px',
      9: '64px',
    },
    zIndices: {
      1: '100',
      2: '200',
      3: '300',
      4: '400',
      max: '999',
    },
  },
  media: {
    bp1: '(min-width: 768px)',
    bp2: '(min-width: 1024px)',
    bp3: '(min-width: 1400px)',
  },
  utils: {
    marginHorizontal: (val: Stitches.PropertyValue<'margin'>) => ({
      marginLeft: val,
      marginRight: val,
    }),
    marginVertical: (val: Stitches.PropertyValue<'margin'>) => ({
      marginTop: val,
      marginBottom: val,
    }),
    paddingHorizontal: (val: Stitches.PropertyValue<'padding'>) => ({
      paddingLeft: val,
      paddingRight: val,
    }),
    paddingVertical: (val: Stitches.PropertyValue<'padding'>) => ({
      paddingTop: val,
      paddingBottom: val,
    }),
  },
  themeMap: {
    ...defaultThemeMap,
    marginHorizontal: 'space' as const,
    marginVertical: 'space' as const,
    paddingHorizontal: 'space' as const,
    paddingVertical: 'space' as const,
  },
})

export const { styled, css, globalCss, keyframes, config, createTheme } = stitches
export type CSS = Stitches.CSS<typeof config> & typeof lightTheme
export type ThemeColorValue = Stitches.PropertyValue<'backgroundColor'>

export const lightTheme = createTheme('light-theme', {
  colors: {
    'base-background-subtle': gray.gray1,
    'base-background-normal': gray.gray2,
    'base-component-bg-normal': gray.gray3,
    'base-component-bg-hover': gray.gray4,
    'base-component-bg-active': gray.gray5,
    'base-border-subtle': gray.gray6,
    'base-border-normal': gray.gray7,
    'base-border-hover': gray.gray8,
    'base-normal': gray.gray9,
    'base-active': gray.gray10,
    'base-text-low': gray.gray11,
    'base-text-high': gray.gray12,
    'base-text-opposite': gray.gray1,

    'primary-background-subtle': blue.blue1,
    'primary-background-normal': blue.blue2,
    'primary-component-bg-normal': blue.blue3,
    'primary-component-bg-hover': blue.blue4,
    'primary-component-bg-active': blue.blue5,
    'primary-border-subtle': blue.blue6,
    'primary-border-normal': blue.blue7,
    'primary-border-hover': blue.blue8,
    'primary-normal': blue.blue9,
    'primary-active': blue.blue10,
    'primary-text-low': blue.blue11,
    'primary-text-high': blue.blue12,
    'primary-text-opposite': blue.blue1,

    'secondary-background-subtle': orange.orange1,
    'secondary-background-normal': orange.orange2,
    'secondary-component-bg-normal': orange.orange3,
    'secondary-component-bg-hover': orange.orange4,
    'secondary-component-bg-active': orange.orange5,
    'secondary-border-subtle': orange.orange6,
    'secondary-border-normal': orange.orange7,
    'secondary-border-hover': orange.orange8,
    'secondary-normal': orange.orange9,
    'secondary-active': orange.orange10,
    'secondary-text-low': orange.orange11,
    'secondary-text-high': orange.orange12,
    'secondary-text-opposite': orange.orange1,

    'success-background-subtle': green.green1,
    'success-background-normal': green.green2,
    'success-component-bg-normal': green.green3,
    'success-component-bg-hover': green.green4,
    'success-component-bg-active': green.green5,
    'success-border-subtle': green.green6,
    'success-border-normal': green.green7,
    'success-border-hover': green.green8,
    'success-normal': green.green9,
    'success-active': green.green10,
    'success-text-low': green.green11,
    'success-text-high': green.green12,
    'success-text-opposite': green.green1,

    'warning-background-subtle': yellow.yellow1,
    'warning-background-normal': yellow.yellow2,
    'warning-component-bg-normal': yellow.yellow3,
    'warning-component-bg-hover': yellow.yellow4,
    'warning-component-bg-active': yellow.yellow5,
    'warning-border-subtle': yellow.yellow6,
    'warning-border-normal': yellow.yellow7,
    'warning-border-hover': yellow.yellow8,
    'warning-normal': yellow.yellow9,
    'warning-active': yellow.yellow10,
    'warning-text-low': yellow.yellow11,
    'warning-text-high': yellow.yellow12,
    'warning-text-opposite': yellow.yellow1,

    'danger-background-subtle': red.red1,
    'danger-background-normal': red.red2,
    'danger-component-bg-normal': red.red3,
    'danger-component-bg-hover': red.red4,
    'danger-component-bg-active': red.red5,
    'danger-border-subtle': red.red6,
    'danger-border-normal': red.red7,
    'danger-border-hover': red.red8,
    'danger-normal': red.red9,
    'danger-active': red.red10,
    'danger-text-low': red.red11,
    'danger-text-high': red.red12,
    'danger-text-opposite': red.red1,
  },
})

export const darkTheme = createTheme('dark-theme', {
  colors: {
    'base-background-subtle': grayDark.gray1,
    'base-background-normal': grayDark.gray2,
    'base-component-bg-normal': grayDark.gray3,
    'base-component-bg-hover': grayDark.gray4,
    'base-component-bg-active': grayDark.gray5,
    'base-border-subtle': grayDark.gray6,
    'base-border-normal': grayDark.gray7,
    'base-border-hover': grayDark.gray8,
    'base-normal': grayDark.gray9,
    'base-active': grayDark.gray10,
    'base-text-low': grayDark.gray11,
    'base-text-high': grayDark.gray12,
    'base-text-opposite': grayDark.gray1,

    'primary-background-subtle': blueDark.blue1,
    'primary-background-normal': blueDark.blue2,
    'primary-component-bg-normal': blueDark.blue3,
    'primary-component-bg-hover': blueDark.blue4,
    'primary-component-bg-active': blueDark.blue5,
    'primary-border-subtle': blueDark.blue6,
    'primary-border-normal': blueDark.blue7,
    'primary-border-hover': blueDark.blue8,
    'primary-normal': blueDark.blue9,
    'primary-active': blueDark.blue10,
    'primary-text-low': blueDark.blue11,
    'primary-text-high': blueDark.blue12,
    'primary-text-opposite': blueDark.blue1,

    'secondary-background-subtle': orangeDark.orange1,
    'secondary-background-normal': orangeDark.orange2,
    'secondary-component-bg-normal': orangeDark.orange3,
    'secondary-component-bg-hover': orangeDark.orange4,
    'secondary-component-bg-active': orangeDark.orange5,
    'secondary-border-subtle': orangeDark.orange6,
    'secondary-border-normal': orangeDark.orange7,
    'secondary-border-hover': orangeDark.orange8,
    'secondary-normal': orangeDark.orange9,
    'secondary-active': orangeDark.orange10,
    'secondary-text-low': orangeDark.orange11,
    'secondary-text-high': orangeDark.orange12,
    'secondary-text-opposite': orangeDark.orange1,

    'success-background-subtle': greenDark.green1,
    'success-background-normal': greenDark.green2,
    'success-component-bg-normal': greenDark.green3,
    'success-component-bg-hover': greenDark.green4,
    'success-component-bg-active': greenDark.green5,
    'success-border-subtle': greenDark.green6,
    'success-border-normal': greenDark.green7,
    'success-border-hover': greenDark.green8,
    'success-normal': greenDark.green9,
    'success-active': greenDark.green10,
    'success-text-low': greenDark.green11,
    'success-text-high': greenDark.green12,
    'success-text-opposite': greenDark.green1,

    'warning-background-subtle': yellowDark.yellow1,
    'warning-background-normal': yellowDark.yellow2,
    'warning-component-bg-normal': yellowDark.yellow3,
    'warning-component-bg-hover': yellowDark.yellow4,
    'warning-component-bg-active': yellowDark.yellow5,
    'warning-border-subtle': yellowDark.yellow6,
    'warning-border-normal': yellowDark.yellow7,
    'warning-border-hover': yellowDark.yellow8,
    'warning-normal': yellowDark.yellow9,
    'warning-active': yellowDark.yellow10,
    'warning-text-low': yellowDark.yellow11,
    'warning-text-high': yellowDark.yellow12,
    'warning-text-opposite': yellowDark.yellow1,

    'danger-background-subtle': redDark.red1,
    'danger-background-normal': redDark.red2,
    'danger-component-bg-normal': redDark.red3,
    'danger-component-bg-hover': redDark.red4,
    'danger-component-bg-active': redDark.red5,
    'danger-border-subtle': redDark.red6,
    'danger-border-normal': redDark.red7,
    'danger-border-hover': redDark.red8,
    'danger-normal': redDark.red9,
    'danger-active': redDark.red10,
    'danger-text-low': redDark.red11,
    'danger-text-high': redDark.red12,
    'danger-text-opposite': redDark.red1,
  },
})

export const globalStyles = globalCss({
  body: {
    backgroundColor: '$base-background-subtle',
    color: '$base-text-hight',
    fontFamily: '$base',
    fontSize: '$3',
    margin: 0,
    transition: 'background-color color 0.25s ease',
    '-webkit-font-smoothing': 'antialiased',
    '-moz-osx-font-smoothing': 'grayscale',
    height: '100vh',
  },
  '*:focus': {
    boxShadow: '$focus',
  },
})
