import {
  PARAGRAPH_OPTIONS,
  HEADING_OPTIONS,
  BLOCKQUOTE_OPTIONS,
  LINK_OPTIONS,
  LIST_OPTIONS,
} from './elements'
import {
  BOLD_OPTIONS,
  ITALIC_OPTIONS,
  CODE_OPTIONS,
  UNDERLINE_OPTIONS,
  STRIKETHROUGH_OPTIONS,
} from './marks'
import {DEFAULTS_TRANSCLUSION} from './TransclusionPlugin'
import {DEFAULTS_IMAGE} from './ImagePlugin'
import {DEFAULTS_BLOCK} from './BlockPlugin'
import {DEFAULTS_BLOCKLIST} from './HierarchyPlugin'

export const options = {
  ...PARAGRAPH_OPTIONS,
  ...HEADING_OPTIONS,
  ...BLOCKQUOTE_OPTIONS,
  ...LINK_OPTIONS,
  ...DEFAULTS_IMAGE,
  ...LIST_OPTIONS,
  ...DEFAULTS_BLOCK,
  ...DEFAULTS_BLOCKLIST,
  ...DEFAULTS_TRANSCLUSION,
  //marks
  ...BOLD_OPTIONS,
  ...ITALIC_OPTIONS,
  ...CODE_OPTIONS,
  ...UNDERLINE_OPTIONS,
  ...STRIKETHROUGH_OPTIONS,
}
