@startuml

' To learn more about the model that diagram uses see: https://c4model.com.

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

LAYOUT_TOP_DOWN

title "Mintter Architecture"

Person(user, "Mintter User")

System_Ext(ipfs_network, "IPFS Network", "P2P content-addressable blob storage.")
System_Ext(mtt_net, "Mintter Network", "Application-specific protocol on top of libp2p.")
System_Ext(libp2p, "Libp2p Network", "General-purpose peer-to-peer network.")

System_Boundary(app, "Mintter Local App"){
    Container_Boundary(mtt, "Mintter P2P Node") {        
        Component(logbook, "Logbook", "Go, BadgerDB, libp2p", "Append-only log, verifiable cryptographically, replicated across the network. Local to each peer.")
        Component(networking, "Networking", "libp2p", "Mintter-specific functionality over libp2p (exchange profile information, announcing documents, managing peers, etc.).")
        Component(cas, "CAS", "IPFS", "Content-addressable storage. Stores the actual data (documents, sections, metadata, etc.).")
        Component(identity, "Identity", "LND Aezeed + BIP39", "Cryptographic identity. Master key seed from which all other keypairs are derived.")
    }

    Container(server, "HTTP Server", "Go, gRPC", "Exposes all the functionality of the app to the frontend.")
    Container(webapp, "Web App", "NextJS (exported to static files)", "Main UI for our users.")
    Container(ln, "Lightning Network", "Go, LND", "Implements Lightning Network features. Details TBD.")
}


Rel_L(server, webapp, "Serves static assets for", "HTTP")
Rel(webapp, server, "Invokes RPCs", "gRPC-Web, HTTP/2")
Rel(user, webapp, "Uses", "Web browser HTTP/1.1")

Rel_R(server, mtt, "Abstracts away")
Rel(server, ln, "Abstract away")
Rel(networking, mtt_net, "Interacts with", "libp2p")
Rel(cas, ipfs_network, "Distributes blobs in")
Rel(logbook, cas, "Points to blobs from")
Rel(logbook, identity, "Signs content cryptographically using")
Rel_R(cas, identity, "Signs content cryptographically using")
Rel_R(ipfs_network, libp2p, "Is built on top of")
Rel_L(mtt_net, libp2p, "Is built on top of")
Rel_L(networking, logbook, "Replicates")


@enduml